### ISSUE TITLE
short time frame data in grafana

### ISSUE THREAD

**Issue by Roconda** [giantswarm/kubernetes-prometheus#57]
Hi,

First of all, very nice work, and very easy installation.

Currently I did a setup but the data stored is a very short time frame. It seems like the data will be truncated each few hours.
Is  there something I might be missing?

Many thanks!

**Comment by dstroot** [comment]
Two thoughts:
1) Make sure you use persistent storage
2) You can save data aa long as you want assuming you have enough storage:

```yml
spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v1.5.2
        args:
          - '-storage.local.retention=72h'         # <++++ Edit this here
          - '-storage.local.path=/prometheus'
          - '-storage.local.memory-chunks=500000'
          - '-config.file=/etc/prometheus/prometheus.yml'
```
