### ISSUE TITLE
cadvisor scrape for prometheus

### ISSUE THREAD

**Issue by RahulMahale** [giantswarm/kubernetes-prometheus#84]
Can I create a PR for kubernetes-cadvisor scrape ?

**Comment by gaya3chandran1** [comment]
Is there any reference for Kubernetes CAdvisor scrape?

**Comment by RahulMahale** [comment]
@gaya3chandran1 I came across this CAdvisor scrape.

```
        - job_name: 'kubernetes-cadvisor'

          scheme: https

          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

          kubernetes_sd_configs:
          - role: node

          relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/proxy/nodes/${1}:4194/metrics 
```
